
# Setup
title:               Corn World Studio
email:               2135620856@qq.com
tagline:             玉米世界工作室
url:                 "https://cornworldstudio.github.io/"
baseurl:             ""

# About/contact
author: # you can edit these to be your personal details
  name:              CornWorld
  url:               
  email:             CornWorld@qq.com

# Google services
google_verification:
# Use either direct GA implementation or set up GTM account
# - using both will skew your data (leave blank to not use at all)
google_analytics:
google_tag_manager:
# Bing services
bing_verification:

# Social
github_username: CornWorld050324
twitter_username: 
instagram_username: 
facebook: 
linkedin_username: 
dribbble_username: 

# Custom vars
version:             1.0.1
github:
  repo:              https://github.com/kevit/devaid-jekyll-theme

# Gems - Dependencies for this theme
gems:
  # None currently

# Build settings
markdown:     kramdown
permalink:    pretty

widgets:
  - title: 关于
    url: about
    archor: true
  - title: 特点
    url: features
    archor: true
  - title: 作品
    url: works
    archor: true
  - title: 联系我们
    url: contact
    archor: true
